# Generated by Django 3.1.1 on 2020-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ManyToManyField(null=True, to='persons.City'),
        ),
    ]
